### ISSUE TITLE
A few dead links in docs and articles

### ISSUE THREAD

**Issue by vkuzel** [thymeleaf/thymeleaf-docs#46]
I discovered some dead links in docs and articles. I actually crawled the site to find them. Btw. there are ton of dead links in forum but it's probably not worth fixing.

On page: http://www.thymeleaf.org/doc/articles/layouts.html
Are dead links pointing to:
* http://www.thymeleaf.org/doc/html/Using-Thymeleaf.html#template-layout
* http://www.thymeleaf.org/doc/html/Using-Thymeleaf.html#appendix-c-dom-selector-syntax
* http://www.thymeleaf.org/doc/html/Using-Thymeleaf.html#parameterizable-fragment-signatures

On page: http://www.thymeleaf.org/download.html
Is dead link:
* https://github.com/thymeleaf/thymeleaf-spring/blob/thymeleaf-spring5-3.0.3.RELEASE/thymeleaf-spring5/ChangeLog.txt

On page: http://www.thymeleaf.org/apidocs/thymeleaf/2.1.3.RELEASE/org/thymeleaf/dom/Node.NodeLocalVariablesMap.html
Are dead links:
* http://java.sun.com/j2se/1.5.0/docs/api/java/util/AbstractMap.SimpleImmutableEntry.html?is-external=true
* http://java.sun.com/j2se/1.5.0/docs/api/java/util/AbstractMap.SimpleEntry.html?is-external=true

On page: http://www.thymeleaf.org/ecosystem.html
Is dead link:
* http://ugate.github.io/thymus

On page: http://www.thymeleaf.org/apidocs/thymeleaf/3.0.3.RELEASE/org/thymeleaf/util/FastStringWriter.html
Is dead link:
* http://docs.oracle.com/javase/6/docs/api/java/lang/AutoCloseable.html?is-external=true

On page: http://www.thymeleaf.org/apidocs/thymeleaf/3.0.3.RELEASE/org/thymeleaf/templateparser/reader/PrototypeOnlyCommentTextReader.html#PrototypeOnlyCommentTextReader-java.io.Reader-
Is dead link:
* http://www.thymeleaf.org/apidocs/thymeleaf/3.0.3.RELEASE/org/thymeleaf/templateparser/reader/BlockAwareReader.BlockAction.html

On page: http://www.thymeleaf.org/whatsnew21.html#spconv
Is dead link:
* http://www.thymeleaf.org/features.html

**Comment by ultraq** [comment]
Thanks for letting us know @vkuzel!  I'll update the ones that cross into the website too and are not generated from this project.

Note to myself:

> On page: http://www.thymeleaf.org/doc/articles/layouts.html
> Are dead links pointing to:
> * http://www.thymeleaf.org/doc/html/Using-Thymeleaf.html#template-layout
> * http://www.thymeleaf.org/doc/html/Using-Thymeleaf.html#appendix-c-dom-selector-syntax
> * http://www.thymeleaf.org/doc/html/Using-Thymeleaf.html#parameterizable-fragment-signatures

These will be taken care by #42, so don't do anything about them.

**Comment by ultraq** [comment]
Reformatted with checkboxes so I can mark ones as done:

---
On page: http://www.thymeleaf.org/doc/articles/layouts.html
* [ ] http://www.thymeleaf.org/doc/html/Using-Thymeleaf.html#template-layout
* [ ] http://www.thymeleaf.org/doc/html/Using-Thymeleaf.html#appendix-c-dom-selector-syntax
* [ ] http://www.thymeleaf.org/doc/html/Using-Thymeleaf.html#parameterizable-fragment-signatures

On page: http://www.thymeleaf.org/download.html
* [ ] https://github.com/thymeleaf/thymeleaf-spring/blob/thymeleaf-spring5-3.0.3.RELEASE/thymeleaf-spring5/ChangeLog.txt

On page: http://www.thymeleaf.org/apidocs/thymeleaf/2.1.3.RELEASE/org/thymeleaf/dom/Node.NodeLocalVariablesMap.html
* [ ] http://java.sun.com/j2se/1.5.0/docs/api/java/util/AbstractMap.SimpleImmutableEntry.html?is-external=true
* [ ] http://java.sun.com/j2se/1.5.0/docs/api/java/util/AbstractMap.SimpleEntry.html?is-external=true

On page: http://www.thymeleaf.org/ecosystem.html
* [ ] http://ugate.github.io/thymus

On page: http://www.thymeleaf.org/apidocs/thymeleaf/3.0.3.RELEASE/org/thymeleaf/util/FastStringWriter.html
* [ ] http://docs.oracle.com/javase/6/docs/api/java/lang/AutoCloseable.html?is-external=true

On page: http://www.thymeleaf.org/apidocs/thymeleaf/3.0.3.RELEASE/org/thymeleaf/templateparser/reader/PrototypeOnlyCommentTextReader.html#PrototypeOnlyCommentTextReader-java.io.Reader-
* [ ] http://www.thymeleaf.org/apidocs/thymeleaf/3.0.3.RELEASE/org/thymeleaf/templateparser/reader/BlockAwareReader.BlockAction.html

On page: http://www.thymeleaf.org/whatsnew21.html#spconv
* [ ] http://www.thymeleaf.org/features.html

**Comment by ultraq** [comment]
@danielfernandez, the unticked javadoc items above have revealed something interesting.  Those links are actually for higher versions of Java SE than what that version of Thymeleaf supports, but, for example, the Thymeleaf 2 doc is trying to link to an item that wasn't added until Java 6.

I've taken a look at our code and I don't think it's doing anything wrong, so it still properly supports the Java versions we say, but I suspect the problem is with maven-javadoc-plugin in that it's autodetecting the JDK on the machine to build the available links but somewhere else is then using the lower Java version's base URL.  I dunno.

**Comment by danielfernandez** [comment]
Note those are for Thymeleaf 2.1.3 (a quite old version -- May 2014), and Thymeleaf 2.1 was Java 5 compatible, not Java 6. So it's normal that it links to the 1.5.0 javadoc. 

BUT note that even if 2.1.3 is Java5-source-compatible, its binaries and javadoc were built using Java 6. And the latest version of that branch, 2.1.5, using Java 8. Still, links are pointing to 1.5.0 because the "source" property of `maven-compiler-plugin` says the source is compatible with 1.5.0.

So, what happens? Well, what happens is that the javadoc tools for versions 6 or 8 determine that those classes inherit those interfaces, because that's what happens in v6/v8's runtimes. And create the links using the base URL for 1.5.0. Which fails, because in 1.5.0 those interfaces didn't exist.

So it's an interaction between the `maven-javadoc-plugin` and the `javadoc` tool itself. I wouldn't worry *at all* about something like this.

**Comment by ultraq** [comment]
Cool, if you're not worried about those, then I'm going to consider this one done.

**Comment by danielfernandez** [comment]
Emanuel, these fixes... did you have to apply any changes on `thymeleaf-dist`? I don't find any new commits there…

**Comment by ultraq** [comment]
The only commits related to this were on the website project: https://github.com/thymeleaf/thymeleaf.github.com/commit/7287d771163eff6a8c8aa2c6cbc260f09411f048  Even then they were for our "obsolete" "What's New?" pages.  The rest had been fixed since the issue was reported.
